all:
	@$(MAKE) -f makefiles/java.mk
	@$(MAKE) -f makefiles/linux.amd64.mk
	@$(MAKE) -f makefiles/linux.i386.mk

clean:
	@$(MAKE) -f makefiles/java.mk clean
	@$(MAKE) -f makefiles/linux.amd64.mk clean
	@$(MAKE) -f makefiles/linux.i386.mk clean
